AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
Rails:
  Enabled: true

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 120

Metrics/ClassLength:
  CountComments: false
  Max: 180

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false
